GameObject Class Reference
#include <GameObject.h>
Public Member Functions
GameObject (std::string Type)
float getX ()
float getY ()
float getZ ()
float getDir ()
float getHeight ()
float getWidth ()
float getDepth ()
std::string getType ()
int getModID ()
void setPosition (Vector4f pos)
void setPosition (float x, float y, float z, float dir)
void setDimensionsY (float hgt)
void setDimensionsX (float wdt)
void setDimensionsZ (float dpt)
void setDimensions (float x, float y, float z)
void setType (std::string Type)
void setModID (int tex)
Detailed Description
Author
Brandon Lim A Game Object Class. A class that stores the different data about a game object, whether it be an NPC, an enemy, or something else.
Definition at line 21 of file GameObject.h.
Constructor & Destructor Documentation
GameObject::GameObject (std::string Type)
A Constructor for the GameObject Class. Constructor for the GameObject Class. Sets enemy to default
Parameters
type the type of the object, NPC, enemy, etc.
Definition at line 5 of file GameObject.cpp.
                                    {
    for(int i = 0; i<4; i++){
        Position[i] = 0;
    }
    type = Type;
}
Member Function Documentation
float GameObject::getDepth () [inline]
Definition at line 46 of file GameObject.h.
{ return depth; }
float GameObject::getDir () [inline]
Definition at line 43 of file GameObject.h.
{ return Position[3]; }
float GameObject::getHeight () [inline]
Definition at line 44 of file GameObject.h.
{ return height; }
int GameObject::getModID () [inline]
Definition at line 48 of file GameObject.h.
{ return modelID; }
std::string GameObject::getType () [inline]
Definition at line 47 of file GameObject.h.
{ return type; }
float GameObject::getWidth () [inline]
Definition at line 45 of file GameObject.h.
{ return width; }
float GameObject::getX () [inline]
Definition at line 40 of file GameObject.h.
{ return Position[0]; }
float GameObject::getY () [inline]
Definition at line 41 of file GameObject.h.
{ return Position[1]; }
float GameObject::getZ () [inline]
Definition at line 42 of file GameObject.h.
{ return Position[2]; }
void GameObject::setDimensions (float x, float y, float z)
Sets the 3 dimensions of the object. A function for setting the dimensions of the object.
Parameters
x the width of the object.
y the height of the object.
z the depth of the object.
Definition at line 45 of file GameObject.cpp.
References setDimensionsX(), setDimensionsY(), and setDimensionsZ().
                                                       {
    setDimensionsX(x);
    setDimensionsY(y);
    setDimensionsZ(z);
}
void GameObject::setDimensionsX (float wdt)
Sets the width of object. A function for setting the width of the object.
Parameters
wdt the width of the object.
Definition at line 33 of file GameObject.cpp.
Referenced by setDimensions().
                                        {
    width = wdt;
}
void GameObject::setDimensionsY (float hgt)
Sets the height of object. A function for setting the height of the object.
Parameters
hgt the height of the object.
Definition at line 29 of file GameObject.cpp.
Referenced by setDimensions().
                                        {
    height = hgt;
}
void GameObject::setDimensionsZ (float dpt)
Sets the z-axis length of object. A function for setting the z-axis length of the object.
Parameters
dpt the depth of the object.
Definition at line 37 of file GameObject.cpp.
Referenced by setDimensions().
                                        {
    depth = dpt;
}
void GameObject::setModID (int tex)
Sets the modelID of the object. A function for setting the modelID to be applied to the object.
Parameters
tex the modelID of the object
Definition at line 41 of file GameObject.cpp.
                                {
    modelID = tex;
}
void GameObject::setPosition (Vector4f pos)
Definition at line 12 of file GameObject.cpp.
                                        {
    for(int i = 0; i < 4; i++){
        Position[i] = pos[i];
    }
}
void GameObject::setPosition (float x, float y, float z, float dir)
Definition at line 18 of file GameObject.cpp.
                                                                {
    Position[0] = x;
    Position[1] = y;
    Position[2] = z;
    Position[3] = dir;
}
void GameObject::setType (std::string Type)
Sets the type of object. A function for setting the type of the object.
Parameters
Type the type of the object. Currently has no validation.
Definition at line 25 of file GameObject.cpp.
                                      {
    type = Type;
}
The documentation for this class was generated from the following files:
GameObject.h
GameObject.cpp