BoundBox Class Reference
#include <BoundBox.h>
Classes
class h
creates AABB and makes a collision check between 2 AABBs
Public Member Functions
BoundBox ()
default constructor for BoundBoxes
BoundBox (types::Vector3D min, types::Vector3D max)
default constructor for BoundBoxes
~BoundBox (void)
default deconstructor for BoundBoxes
Intersection IntersectAABB (const BoundBox other) const
checks for collisions between 2 BoundBoxes
types::Vector3D & GetMin_Extents ()
getter for min_extents
types::Vector3D & GetMax_Extents ()
getter for max_extents
void setMax_Extents (types::Vector3D)
setter for max_extents
void setMin_Extents (types::Vector3D)
setter for min_extents
Detailed Description
Definition at line 10 of file BoundBox.h.
Constructor & Destructor Documentation
BoundBox::BoundBox ()
default constructor for BoundBoxes
Definition at line 3 of file BoundBox.cpp.
                  {
}
BoundBox::BoundBox (types::Vector3D min, types::Vector3D max)
default constructor for BoundBoxes
Parameters
min- types::Vector3D, max - types::Vector3D
Definition at line 7 of file BoundBox.cpp.
                                                      {
    min_extents = min;
    max_extents = max;
}
BoundBox::~BoundBox (void)
default deconstructor for BoundBoxes
Definition at line 14 of file BoundBox.cpp.
                       {
    
}
Member Function Documentation
types::Vector3D & BoundBox::GetMax_Extents ()
getter for max_extents
Returns
Intersection
Definition at line 52 of file BoundBox.cpp.
Referenced by IntersectAABB().
                                       {
    return max_extents;
}
types::Vector3D & BoundBox::GetMin_Extents ()
getter for min_extents
Returns
Intersection
Definition at line 48 of file BoundBox.cpp.
Referenced by IntersectAABB().
                                       {
    return min_extents;
}
Intersection BoundBox::IntersectAABB (const BoundBox other) const
checks for collisions between 2 BoundBoxes
Parameters
other - BoundBox
Returns
Intersection
Definition at line 18 of file BoundBox.cpp.
References GetMax_Extents(), GetMin_Extents(), Intersection::Intersection(), types::Vector3D::max(), types::Vector3D::x, types::Vector3D::y, and types::Vector3D::z.
                                                         {
    types::Vector3D distances;// = other.GetMin_Extents() - max_extents;
    distances.x = other.GetMin_Extents().x - max_extents.x;
    distances.y = other.GetMin_Extents().y - max_extents.y;
    distances.z = other.GetMin_Extents().z - max_extents.z;
    types::Vector3D distances2;
    distances2.x = min_extents.x - other.GetMax_Extents().x;
    distances2.y = min_extents.y - other.GetMax_Extents().y;
    distances2.z = min_extents.z - other.GetMax_Extents().z;
    types::Vector3D distance = distances.max(distances2);
    float maxDistance = distance.max();
    /*
    if(maxDistance<0){
        return true;
    }else{
        return false;
    }
    */
    /*
    return(min_extents.x <= other.GetMax_Extents().x && max_extents.x >= other.GetMin_Extents().x) &&
         (min_extents.y <= other.GetMax_Extents().y && max_extents.y >= other.GetMin_Extents().y) &&
         (min_extents.z <= other.GetMax_Extents().z && max_extents.z >= other.GetMin_Extents().z);
         */
    return Intersection(maxDistance >0, maxDistance);
}
void BoundBox::setMax_Extents (types::Vector3D max)
setter for max_extents
Parameters
types::Vector3D
Definition at line 56 of file BoundBox.cpp.
                                              {
    max_extents = max;
}
void BoundBox::setMin_Extents (types::Vector3D min)
setter for min_extents
Parameters
types::Vector3D
Definition at line 60 of file BoundBox.cpp.
                                              {
    min_extents = min;
}
The documentation for this class was generated from the following files:
BoundBox.h
BoundBox.cpp