types Namespace Reference
Classes
struct Matrix4x4
A struct that defines a four-dimensional matrix.
struct Vector2D
A struct that defines a vector in two-dimensional space.
struct Vector3D
A struct that defines a vector in three-dimensional space.
struct Vector4D
A struct that defines a vector in three-dimensional space with an extra value that defines whether it is a point or a proper vector.
Functions
Vector4D operator* (const Matrix4x4 &m, const Vector4D &v)
An overridden multiplication operator for matrix * vector calculations.
Vector4D operator* (const Vector4D &v, const Matrix4x4 &m)
An overridden multiplication operator for vector * matrix calculations.
Matrix4x4 operator* (const Matrix4x4 &m1, const Matrix4x4 &m2)
An overridden multiplication operator for matrix multiplication.
Detailed Description
Types.h
Author: Alfred Malone Date: 23/4/2017
Defines a set of types for use in calculations on transformations in 3D space.
Vectors of three types and a matrix type.
Function Documentation
Vector4D types::operator* (const Matrix4x4 & m, const Vector4D & v)
An overridden multiplication operator for matrix * vector calculations.
Parameters
m - The matrix to be multiplied
v - The vector to be multiplied
Returns
Vector4D - The vector resulting from the operation
This simply overrides the multiplication operator to reflect how pre-multiplying a vector with a matrix operates.
Definition at line 5 of file Types.cpp.
References types::Matrix4x4::columns, types::Vector4D::Vector4D(), types::Vector4D::w, types::Vector4D::x, types::Vector4D::y, and types::Vector4D::z.
Referenced by operator*().
                                                              {
    return Vector4D((m.columns[0].x * v.x) + (m.columns[1].
      x * v.y) + (m.columns[2].x * v.z) + (m.columns[3].x * v.w),
                    (m.columns[0].y * v.x) + (m.columns[1].y * v.
      y) + (m.columns[2].y * v.z) + (m.columns[3].y * v.w),
                    (m.columns[0].z * v.x) + (m.columns[1].z * v.
      y) + (m.columns[2].z * v.z) + (m.columns[3].z * v.w),
                    (m.columns[0].w * v.x) + (m.columns[1].w * v.
      y) + (m.columns[2].w * v.z) + (m.columns[3].w * v.w));
}
Vector4D types::operator* (const Vector4D & v, const Matrix4x4 & m)
An overridden multiplication operator for vector * matrix calculations.
Parameters
v - The vector to be multiplied
m - The matrix to be multiplied
Returns
Vector4D - The vector resulting from the operation
This simply overrides the multiplication operator to reflect how post-multiplying a vector with a matrix operates.
Definition at line 12 of file Types.cpp.
References types::Matrix4x4::columns, types::Vector4D::Vector4D(), types::Vector4D::w, types::Vector4D::x, types::Vector4D::y, and types::Vector4D::z.
                                                              {
    return Vector4D((v.x * m.columns[0].x) + (v.y * m.columns[0].
      y) + (v.z * m.columns[0].z) + (v.w * m.columns[0].w),
                    (v.x * m.columns[1].x) + (v.y * m.columns[1].
      y) + (v.z * m.columns[1].z) + (v.w * m.columns[1].w),
                    (v.x * m.columns[2].x) + (v.y * m.columns[2].
      y) + (v.z * m.columns[2].z) + (v.w * m.columns[2].w),
                    (v.x * m.columns[3].x) + (v.y * m.columns[3].
      y) + (v.z * m.columns[3].z) + (v.w * m.columns[3].w));
}
Matrix4x4 types::operator* (const Matrix4x4 & m1, const Matrix4x4 & m2)
An overridden multiplication operator for matrix multiplication.
Parameters
m1 - The matrix to be pre-multiplied
m2 - The matrix to be post-multiplied
Returns
Matrix4x4 - The matrix resulting from the operation
This simply overrides the multiplication operator to reflect how matrix multiplication operates.
Definition at line 19 of file Types.cpp.
References types::Matrix4x4::columns, types::Matrix4x4::Matrix4x4(), and operator*().
                                                                  {
    Vector4D X = m1 * m2.columns[0];
    Vector4D Y = m1 * m2.columns[1];
    Vector4D Z = m1 * m2.columns[2];
    Vector4D W = m1 * m2.columns[3];
 
    return Matrix4x4(X, Y, Z, W);
}