types::Matrix4x4 Struct Reference
A struct that defines a four-dimensional matrix.
#include <Types.h>
Public Member Functions
Matrix4x4 ()
Matrix4x4 (Vector4D col1, Vector4D col2, Vector4D col3, Vector4D col4)
Public Attributes
Vector4D columns [4]
The columns of the matrix.
Detailed Description
A struct that defines a four-dimensional matrix.
The Matrix4x4 struct is a data type that represents a four-dimensional matrix. This is useful for spatial calculations or for storing four-dimensional vectors.
Author
Alfred Malone
Version
01
Date
23/4/2017 Alfred Malone, created basic class
Author
Alfred Malone
Version
02
Date
24/4/2017 Alfred Malone, added copy constructor
Bug
Bug This one, while requiring explanation, is also simple. No bugs.
Definition at line 329 of file Types.h.
Constructor & Destructor Documentation
types::Matrix4x4::Matrix4x4 () [inline]
The constructor for a Matrix4x4 variable. Initialises all of the elements of the matrix.
Definition at line 337 of file Types.h.
References columns, and types::Vector4D::Vector4D().
                   {
            columns[0] = Vector4D(1, 0, 0, 0);
            columns[1] = Vector4D(0, 1, 0, 0);
            columns[2] = Vector4D(0, 0, 1, 0);
            columns[3] = Vector4D(0, 0, 0, 1);
        }
types::Matrix4x4::Matrix4x4 (Vector4D col1, Vector4D col2, Vector4D col3, Vector4D col4) [inline]
Another constructor for a Matrix4x4 variable. Initialises the columns of the matrix with col1, col2, col3, and col4.
Definition at line 348 of file Types.h.
References columns.
Referenced by Camera::Camera(), and types::operator*().
                                                                             {
            columns[0] = col1;
            columns[1] = col2;
            columns[2] = col3;
            columns[3] = col4;
        }
Member Data Documentation
Vector4D types::Matrix4x4::columns[4]
The columns of the matrix.
Definition at line 331 of file Types.h.
Referenced by Matrix4x4(), types::operator*(), and Camera::transformView().
The documentation for this struct was generated from the following file:
Types.h