types::Vector4D Struct Reference
A struct that defines a vector in three-dimensional space with an extra value that defines whether it is a point or a proper vector.
#include <Types.h>
Public Member Functions
Vector4D ()
Vector4D (float xx, float yy, float zz, float ww)
float length ()
Gets the length of the vector.
Vector4D normalise ()
Gets the normalised version of the vector.
Public Attributes
float x
float y
float z
float w
Detailed Description
A struct that defines a vector in three-dimensional space with an extra value that defines whether it is a point or a proper vector.
The Vector4D struct is a data type that represents a vector or point in three- dimensional space, the two of which can be discerned between with the w-value. A few functions are provided to assist with spatial calculations. This type was created so that 3D vectors could be used in matrix multiplication.
Author
Alfred Malone
Version
01
Date
23/4/2017 Alfred Malone, created basic class
Author
Alfred Malone
Version
02
Date
24/4/2017 Alfred Malone, added extra functions for calculations
Bug
Bug This one, while requiring explanation, is also simple. No bugs.
Definition at line 249 of file Types.h.
Constructor & Destructor Documentation
types::Vector4D::Vector4D () [inline]
The constructor for a Vector4D variable. Initialises the x, y, z, and w values.
Definition at line 259 of file Types.h.
References w, x, y, and z.
Referenced by normalise().
                  {
            x = 0.0f;
            y = 0.0f;
            z = 0.0f;
            w = 1.0f;
        }
types::Vector4D::Vector4D (float xx, float yy, float zz, float ww) [inline]
Another constructor for a Vector4D variable. Initialises the x, y, z, and w values with xx, yy, zz, and ww respectively.
Definition at line 270 of file Types.h.
References w, x, y, and z.
Referenced by Camera::Camera(), types::Matrix4x4::Matrix4x4(), types::operator*(), and Camera::transformView().
                                                        {
            x = xx;
            y = yy;
            z = zz;
            w = ww;
        }
Member Function Documentation
float types::Vector4D::length () [inline]
Gets the length of the vector.
Returns
float - The vector's length as a floating-point number
length calculates and returns the length of the vector (after determining if it is a vector) using its x, y, and z values.
Definition at line 284 of file Types.h.
References z.
Referenced by normalise().
                      {
            if(z != 0.0f)
                return (sqrt(x*x + y*y + z*z));
            else
                return 0.0f;
        }
Vector4D types::Vector4D::normalise () [inline]
Gets the normalised version of the vector.
Returns
Vector4D - The normalised vector
normalise calculates and returns the normalised version of the vector using its x, y, and z values.
Definition at line 298 of file Types.h.
References length(), Vector4D(), x, y, and z.
                            {
            Vector4D normalVec = Vector4D();
            float length = this->length();
            if(length != 0){
                normalVec.x = x / length;
                normalVec.y = y / length;
                normalVec.z = z / length;
            }
            return normalVec;
        }
Member Data Documentation
float types::Vector4D::w
Definition at line 253 of file Types.h.
Referenced by types::operator*(), and Vector4D().
float types::Vector4D::x
Definition at line 250 of file Types.h.
Referenced by normalise(), types::operator*(), and Vector4D().
float types::Vector4D::y
Definition at line 251 of file Types.h.
Referenced by normalise(), types::operator*(), and Vector4D().
float types::Vector4D::z
Definition at line 252 of file Types.h.
Referenced by length(), normalise(), types::operator*(), and Vector4D().
The documentation for this struct was generated from the following file:
Types.h