types::Vector2D Struct Reference
A struct that defines a vector in two-dimensional space.
#include <Types.h>
Public Member Functions
Vector2D ()
Vector2D (float xx, float yy)
float length ()
Gets the length of the vector.
Vector2D normalise ()
Gets the normalised version of the vector.
Public Attributes
float x
The x-axis value of the vector.
float y
The y-axis value of the vector.
Detailed Description
A struct that defines a vector in two-dimensional space.
The Vector2D struct is merely a data type that represents a vector in two-dimensional space, providing a few functions to assist with spatial calculations. At present, it does not appear to be used.
Author
Alfred Malone
Version
01
Date
23/4/2017 Alfred Malone, created basic class
Author
Alfred Malone
Version
02
Date
24/4/2017 Alfred Malone, added extra functions for calculations
Bug
Bug Shouldn't be any, it's quite a simple struct.
Definition at line 34 of file Types.h.
Constructor & Destructor Documentation
types::Vector2D::Vector2D () [inline]
The constructor for a Vector2D variable. Initialises the x and y values.
Definition at line 44 of file Types.h.
References x, and y.
Referenced by normalise().
                  {
            x = 0.0f;
            y = 0.0f;
        }
types::Vector2D::Vector2D (float xx, float yy) [inline]
Another constructor for a Vector2D variable. Initialises the x and y values with xx and yy respectively.
Definition at line 53 of file Types.h.
References x, and y.
                                    {
            x = xx;
            y = yy;
        }
Member Function Documentation
float types::Vector2D::length () [inline]
Gets the length of the vector.
Returns
float - The vector's length as a floating-point number
length calculates and returns the length of the vector using its x and y values.
Definition at line 64 of file Types.h.
Referenced by normalise().
                      {
            return (sqrt(x*x + y*y));
        }
Vector2D types::Vector2D::normalise () [inline]
Gets the normalised version of the vector.
Returns
Vector2D - The normalised vector
normalise calculates and returns the normalised version of the vector using its x and y values.
Definition at line 75 of file Types.h.
References length(), Vector2D(), x, and y.
                            {
            Vector2D normalVec = Vector2D();
            float length = this->length();
            if(length != 0){
                normalVec.x = x / length;
                normalVec.y = y / length;
            }
            return normalVec;
        }
Member Data Documentation
float types::Vector2D::x
The x-axis value of the vector.
Definition at line 36 of file Types.h.
Referenced by normalise(), and Vector2D().
float types::Vector2D::y
The y-axis value of the vector.
Definition at line 38 of file Types.h.
Referenced by normalise(), and Vector2D().
The documentation for this struct was generated from the following file:
Types.h